version: '3.2'
services: 
  bot:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: fbbot
    ports: 
      - "${PORT}:${PORT}"
    volumes:
      - type: bind
        source: ${PRIVKEYPATH}
        target: ${PRIVKEYPATH} 
      - type: bind
        source: ${CERTPEMPATH}
        target: ${CERTPEMPATH}
      - type: bind
        source: ${FULLCHAINPEMPATH}
        target: ${FULLCHAINPEMPATH}
