version: '3.2'
services: 
  bot:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: fbbot
    ports: 
      - "${PORT}:${PORT}"
    volumes:
      - type: bind
        source: ./privkey.pem
        target: ${PRIVKEYPATH} 
      - type: bind
        source: ./cert.pem
        target: ${CERTPEMPATH}
      - type: bind
        source: ./fullchain.pem
        target: ${FULLCHAINPEMPATH}
