version: '3.2'
services: 
  bot:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: fbbot
    ports: 
      - "${PORT}:${PORT}"
    volumes:
      - type: bind
        source: /etc/letsencrypt/live/www.psifbbot.tk/privkey.pem
        target: ${PRIVKEYPATH} 
      - type: bind
        source: /etc/letsencrypt/live/www.psifbbot.tk/cert.pem
        target: ${CERTPEMPATH}
      - type: bind
        source: /etc/letsencrypt/live/www.psifbbot.tk/fullchain.pem
        target: ${FULLCHAINPEMPATH}
